Allow serving static assets from `baseDir`
fastify/fastify-swagger-ui pull request #108
Opened 2023-12-06 12:08 UTC by davidjbng

Resolves #65 

This PR documents how to server static swagger-ui files from a custom directory and fixes serving static assets from when the `baseDir` option is set.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-12-06 14:37 UTC, mcollina approved these changes
lgtm

2023-12-06 15:20 UTC, Fdawgs requested changes
Few issues with doc changes.
Will flesh this out once I'm finished at work.

2023-12-12 10:23 UTC, mcollina commented
@Fdawgs ptal

2023-12-12 17:09 UTC, Fdawgs requested changes

2023-12-12 17:09 UTC, Fdawgs commented on README.md
> +
```suggestion
To bundle Swagger UI with your application, the swagger-ui static files need to be copied to the server and the `baseDir` option set to point to the file directory.

```

2023-12-13 09:44 UTC, Fdawgs approved these changes

2023-12-14 23:19 UTC, DavidTanner commented
Any idea on when this can be merged?

2023-12-15 00:30 UTC, merged