[Feature] href for logo (with optional target="_blank")
fastify/fastify-swagger-ui pull request #171
Opened 2024-08-08 22:39 UTC by breftejk

#### Checklist

- [ +] run `npm run test` and `npm run benchmark`
- [ +] tests and/or benchmarks are included
- [ +] documentation is changed or added
- [ +] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-08-09 09:11 UTC, mcollina commented
the tests are failing

2024-08-09 09:55 UTC, Uzlopak requested changes, later dismissed
I would make it actually simpler

2024-08-09 09:55 UTC, Uzlopak commented on types/index.d.ts
> +    }
I would actually say, that the logo gets a href and a target and not an object

```suggestion
    href?: string;
    target?: '_blank' | '_parent' | '_self' | '_top';
```

2024-08-09 09:55 UTC, Uzlopak commented on lib/swagger-initializer.js
> +  const logoHref = opts.logo.href
const logoHref = opts.logo.href
const logoTarget = opts.logo.target

2024-08-09 09:55 UTC, Uzlopak commented on lib/swagger-initializer.js
> +        }
Would prefer this:

```suggestion
        img.href = logoHref || resolveUrl('/')
        logoTarget && (img.target = logoTarget)
```

2024-08-19 08:59 UTC, Uzlopak commented on README.md
> +    }
can you fix this too, plz?

2024-08-19 09:01 UTC, breftejk commented on README.md
> +    }
I am literally just doing it, sec

2024-08-21 06:51 UTC, breftejk commented
What is with this test error? I dont get it. Everything's fine on my test yet still this weird error on GitHub.

2024-08-21 06:55 UTC, climba03003 commented
Ignore the `pnpm` one, but `e2e` must be pass.

2024-09-17 02:50 UTC, Uzlopak commented
@climba03003 PTAL

2024-09-17 03:25 UTC, climba03003 approved these changes

2024-09-17 08:02 UTC, mcollina approved these changes
lgtm

2024-09-17 11:11 UTC, merged