add theme option
fastify/fastify-swagger-ui pull request #39
Opened 2023-02-17 14:34 UTC by Uzlopak

Closes #13 
Closes #35
Closes #38

First we should discuss if the approach is OK or not. So basically I introduce a theme option. The theme option can handle additional javascript, additional css files and additional favicons. See the corresponding typescript interface. 
I guess we need also to calculate the CSP of the files on plugin load, which is not yet implemented but should be a no-brainer.

So lets discuss if it is the right approach. 

So for the request of @OkanPinar in #35 you would do:

```js
'use strict'

const fastify = require('fastify')({ logger: true })
const { SwaggerTheme } = require('swagger-themes');

fastify.register(require('@fastify/swagger'), {
  mode: 'static',
  specification: {
    path: './examples/example-static-specification.json'
  }
})
fastify.register(require('../index'), {
  theme: {
    css: [
      { filename: 'theme.css', content: new SwaggerTheme('v3').getBuffer('dark') }
    ],
  }
})

fastify.listen({ port: 3000 }, (err) => {
  if (err) throw err
})
```

Taking the example of @Xpucmoc-Bockpec for #13 

```js
'use strict'

const fastify = require('fastify')({ logger: true })
const css = `h2 + a, section .models, .download-url-wrapper {
  display: none!important;
}

.topbar {
  background-color: #002f6c!important;
}

.opblock-get .opblock-summary-method {
  background-color: #0048a6!important;
}

.topbar-wrapper {
  height: 45px;
  background-repeat: no-repeat;
  background-size: contain;
  background-image: url("hello.svg");
}

.topbar-wrapper img {
  display: none;
}`

fastify.register(require('@fastify/swagger'), {
  mode: 'static',
  specification: {
    path: './examples/example-static-specification.json'
  }
})
fastify.register(require('../index'), {
  theme: {
    css: [
      { filename: 'theme.css', content: css }
    ],
  }
})

fastify.listen({ port: 3000 }, (err) => {
  if (err) throw err
})

```

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-02-17 14:41 UTC, mcollina commented
Can you include one or two examples of this customization?

2023-02-17 14:54 UTC, Uzlopak commented
The Logo is an image and that image is the 64x64 favicon. So the answer is yes, but on the other hand also kind of not that "clever" as it is not possible to completely theme the swagger documentation. 

Maybe it makes more sense to have a theme option which basically mounts a folder with fastify-static to `/static/theme`. And we basically expect that the theme folder contains a index.css with the overriding css or maybe index.html overriding everything. Benefit of that would be, that an implementer could put all files into the theme-folder, reducing the configuration overhead and be in full controle of the output.

2023-02-17 15:20 UTC, mcollina commented
I think that would be better.

2023-02-17 19:30 UTC, Uzlopak commented
Mounting the theme folder seems to be elegant, but then it is not easy to just hook those swagger-themes.

2023-02-17 20:28 UTC, mcollina commented
Let's land this and see. Tests are failihg

2023-02-17 21:49 UTC, Uzlopak commented
I will probably implement it tomorrow

2023-02-18 09:17 UTC, ilyamixaltik commented
As support for the swagger-themes library will be added, please write. I will update the library documentation.

2023-03-01 10:40 UTC, ilyamixaltik commented
Are there any successes?

2023-03-01 18:40 UTC, Eomm approved these changes
Added docs

Great feature 🔝

2023-03-01 18:40 UTC, Eomm commented on examples/theme.js
> +  if (err) throw err
```suggestion
  if (err) throw err
  fastify.log.info('Visit the documentation at http://127.0.0.1:3000/documentation/')
```

2023-03-02 17:05 UTC, Fdawgs requested changes

2023-03-02 17:05 UTC, Fdawgs commented on README.md
> + | theme                | {}               | Allow to add custom javascript and css to the Swagger UI web page |
```suggestion
 | theme                | {}               | Add custom JavaScript and CSS to the Swagger UI web page |
```

2023-03-02 17:05 UTC, Fdawgs commented on README.md
> +You can add custom javascript and css to the Swagger UI web page by using the theme option.
```suggestion
You can add custom JavaScript and CSS to the Swagger UI web page by using the theme option.
```

2023-03-02 17:49 UTC, Fdawgs approved these changes

2023-03-03 11:03 UTC, merged