test: add e2e tests with playwright
fastify/fastify-swagger-ui pull request #99
Opened 2023-11-07 23:21 UTC by msebastianb

**Changes**
- Add and configure playwright to the project
- Add command to run tests
- Implement some tests for current features

Closes https://github.com/fastify/fastify-swagger-ui/issues/98

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-11-08 06:58 UTC, Fdawgs requested changes

2023-11-08 06:58 UTC, Fdawgs commented on .gitignore
> +/playwright/.cache/
Duplicates

2023-11-08 06:58 UTC, Fdawgs commented on playwright.config.js
> +const { defineConfig, devices } = require('@playwright/test')
Missing use strict directive

2023-11-08 06:58 UTC, Fdawgs commented on .github/workflows/playwright.yml
> +    branches: [ main, master ]
Should follow the same triggers as the main ci workflow

2023-11-08 06:58 UTC, Fdawgs commented on .github/workflows/playwright.yml
> +        node-version: 18
use `lts/*`

2023-11-08 06:58 UTC, Fdawgs commented on .github/workflows/playwright.yml
> +        retention-days: 30
What would we use this for?

2023-11-08 18:51 UTC, msebastianb commented on .github/workflows/playwright.yml
> +        retention-days: 30
It may not be useful here.

2023-11-08 19:05 UTC, Uzlopak commented
Hmm. problem is, that automerge is in the ci.yml and playwright is not taken into account. So it could result in merging a PR despite the playwright wf failed.

2023-11-09 18:38 UTC, Eomm reviewed
> Hmm. problem is, that automerge is in the ci.yml and playwright is not taken into account. So it could result in merging a PR despite the playwright wf failed.

I think we could merge this new job in the existing one:
https://github.com/fastify/fastify-swagger-ui/blob/master/.github/workflows/ci.yml

then we can run playwright first if I'm not wrong

2023-11-09 18:38 UTC, Eomm commented on .github/workflows/playwright.yml
> +      run: npx playwright install chromium --with-deps
```suggestion
      run: npx playwright@1 install chromium --with-deps
```

2023-11-09 18:38 UTC, Eomm commented on .github/workflows/playwright.yml
> +      run: npx playwright test
```suggestion
      run: npx playwright@1 test
```

2023-11-10 09:06 UTC, Uzlopak commented
maybe put everything into the test script of package.json/npm.

2023-11-13 22:07 UTC, Uzlopak approved these changes
Its odd because the integration tests should run after the unit tests, but it works for me...

But lets see what the others say.

2023-11-14 07:58 UTC, Fdawgs commented
CI isn't happy :/

2023-11-14 08:13 UTC, msebastianb commented
@Fdawgs WDYM?

2023-11-14 08:28 UTC, Fdawgs commented
> @Fdawgs WDYM?

It's happy now, don't worry 😊

2023-11-14 17:56 UTC, Fdawgs requested changes

2023-11-14 17:56 UTC, Fdawgs commented on .github/workflows/playwright.yml
> +jobs:
Can you declare the job permissions please? Last change I promise :D

2023-11-15 08:14 UTC, Fdawgs approved these changes

2023-11-15 16:33 UTC, mcollina approved these changes
lgtm

2023-11-15 16:34 UTC, merged